In [2]:
import pandas as pd
import numpy as np

# Leer datos Clase/codes/datos_5_ej5.csv
df_datos = pd.read_csv('../Clase/codes/datos_5_ej5.csv') 
df_datos.head()

,x1,x2,x3,x4,x5,y
0,3.83,28.87,7.20,26.6,6.19,37.01
1,2.89,20.10,-11.71,24.4,5.17,26.51
2,2.86,69.05,12.32,25.7,7.04,36.51
3,2.92,65.40,14.28,25.7,7.10,40.70
4,3.06,29.59,6.31,25.4,6.15,37.10


In [5]:
# Convertir y a numpy array
y = df_datos['y'].values

# Convertir x1 a x5 a numpy array en una matriz X y agregar una columna de unos para el término independiente
X = df_datos[['x1', 'x2', 'x3', 'x4', 'x5']].values
X = np.hstack((np.ones((X.shape[0], 1)), X))    
X

array([[ 1.000e+00,  3.830e+00,  2.887e+01,  7.200e+00,  2.660e+01,
         6.190e+00],
       [ 1.000e+00,  2.890e+00,  2.010e+01, -1.171e+01,  2.440e+01,
         5.170e+00],
       [ 1.000e+00,  2.860e+00,  6.905e+01,  1.232e+01,  2.570e+01,
         7.040e+00],
       [ 1.000e+00,  2.920e+00,  6.540e+01,  1.428e+01,  2.570e+01,
         7.100e+00],
       [ 1.000e+00,  3.060e+00,  2.959e+01,  6.310e+00,  2.540e+01,
         6.150e+00],
       [ 1.000e+00,  2.070e+00,  4.482e+01,  6.160e+00,  2.160e+01,
         6.410e+00],
       [ 1.000e+00,  2.520e+00,  7.737e+01,  1.270e+01,  2.490e+01,
         6.860e+00],
       [ 1.000e+00,  2.450e+00,  2.467e+01, -1.700e-01,  2.501e+01,
         5.780e+00],
       [ 1.000e+00,  3.130e+00,  6.501e+01,  9.850e+00,  2.660e+01,
         6.510e+00],
       [ 1.000e+00,  2.440e+00,  9.990e+00, -5.000e-02,  2.801e+01,
         5.570e+00],
       [ 1.000e+00,  2.090e+00,  1.220e+01, -1.286e+01,  2.351e+01,
         5.620e+00],
       [ 1.000e+00,  

In [6]:
# Obtener coeficientes de regresión lineal manualmente

# Calcular (X^T X)^(-1)
XtX_inv = np.linalg.inv(X.T @ X)
# Calcular (X^T y)
Xty = X.T @ y
# Calcular coeficientes: beta = (X^T X)^(-1) X^T y
beta = XtX_inv @ Xty
beta

array([19.94856503, -1.79333327,  0.04360156,  0.55576006,  1.11016839,
       -1.81092194])

In [17]:
# Calcular Standard Error de los coeficientes
# Calcular predicciones
y_pred = X @ beta
# Calcular residuos
residuos = y - y_pred
residuos

# Calcular varianza de los residuos
var_residuos = np.sum(residuos**2) / (X.shape[0] - X.shape[1])
var_residuos

# Calcular varianza de los coeficientes: Var(beta) = var_residuos * (X^T X)^(-1)
var_beta = var_residuos * XtX_inv
var_beta

# Calcular Standard Error: SE(beta) = sqrt(Var(beta))
se_beta = np.sqrt(np.diag(var_beta))
se_beta


array([13.62754835,  1.23339617,  0.05325887,  0.09295638,  0.43376789,
        2.02738916])

In [18]:
# Calcular t-statistic: t = beta / SE(beta)
t_statistic = beta / se_beta
t_statistic

array([ 1.46384108, -1.45397992,  0.81867232,  5.97871875,  2.5593605 ,
       -0.89322858])

In [19]:
beta

array([19.94856503, -1.79333327,  0.04360156,  0.55576006,  1.11016839,
       -1.81092194])